const state={user:null,apiBase:(window.NUSASEC_API_BASE||localStorage.getItem('nusasec_api_base')||'').replace(/\/$/,'')};
const cache=new Map(),pending=new Map();
function resolveApi(path){const n=path.startsWith('/')?path:`/${path}`;if(n.startsWith('/api/'))return `${state.apiBase}${n}`;if(n.startsWith('/v1/'))return `${state.apiBase}/api${n}`;return `${state.apiBase}/api/v1${n}`;}
async function api(path,options={}){const method=(options.method||'GET').toUpperCase(),url=resolveApi(path),key=`${method}:${url}`;if(method==='GET'&&!options.noCache){const hit=cache.get(key);if(hit&&Date.now()-hit.time<(options.cacheTtl??30000))return hit.data;if(pending.has(key))return pending.get(key)}const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),options.timeout||7000);const run=(async()=>{try{const headers={...(options.body?{'Content-Type':'application/json'}:{}),...(options.headers||{})};const response=await fetch(url,{...options,credentials:'include',headers,signal:options.signal||controller.signal});if(!response.ok){const error=new Error(`API ${response.status}`);error.status=response.status;throw error}const data=response.status===204?null:await response.json();if(method==='GET'&&!options.noCache)cache.set(key,{time:Date.now(),data});return data}finally{clearTimeout(timer);pending.delete(key)}})();if(method==='GET'&&!options.noCache)pending.set(key,run);return run}
function prefetch(path,options={}){return api(path,{...options,cacheTtl:options.cacheTtl??30000}).catch(()=>null)}
function configureApiBase(value){state.apiBase=String(value||'').replace(/\/$/,'');if(state.apiBase)localStorage.setItem('nusasec_api_base',state.apiBase);else localStorage.removeItem('nusasec_api_base');cache.clear();pending.clear()}
function invalidate(path){const target=resolveApi(path);for(const key of cache.keys())if(key.includes(target))cache.delete(key)}
async function checkCore(options={}){if(!state.apiBase)return{ok:false,reason:'not-configured'};try{await api('/health',{...options,noCache:true,timeout:options.timeout||3000});return{ok:true}}catch(e){return{ok:false,reason:e.name==='AbortError'?'timeout':e.status||'offline'}}}
function showCoreStatus(status,message){document.querySelectorAll('[data-core-status]').forEach(el=>{el.className=`p8-banner ${status}`;el.innerHTML=`<span><i></i>${message}</span>${status==='err'?'<button class="p8-retry" data-core-retry>Retry</button>':''}`;el.querySelector('[data-core-retry]')?.addEventListener('click',()=>window.NusaSec.checkAndRenderStatus())})}
async function checkAndRenderStatus(){const r=await checkCore();showCoreStatus(r.ok?'ok':r.reason==='not-configured'?'warn':'err',r.ok?'NusaSec Core connected':r.reason==='not-configured'?'NusaSec Core endpoint not configured':'NusaSec Core unavailable') ;return r}
window.NusaSec={api,state,resolveApi,configureApiBase,prefetch,invalidate,checkCore,checkAndRenderStatus,showCoreStatus,clearCache:()=>cache.clear()};
document.addEventListener('DOMContentLoaded',()=>{document.querySelectorAll('[data-action="logout"]').forEach(el=>el.addEventListener('click',async event=>{event.preventDefault();try{await api('/auth/logout',{method:'POST',timeout:4000,noCache:true})}finally{location.href='../login/'}}));document.querySelectorAll('[data-core-status]').forEach(()=>checkAndRenderStatus())});
