(() => {
const root=document.getElementById('security-root'); if(!root)return;
const cfg={
 attack:{title:'Know what is exposed.',eyebrow:'ATTACK SURFACE',desc:'Discover assets, external exposure and the context behind each resource.',api:'/v1/product/assets',stats:['Assets','Internet exposure','Risk context','Latest scan'],entity:'assets',empty:'No assets are available from the current NusaSec Core scan.',detail:'/v1/product/assets/{id}/dossier'},
 threat:{title:'Understand risk relationships.',eyebrow:'RISK & THREAT INTELLIGENCE',desc:'Explore attack paths and the relationships that connect assets to security risk.',api:'/v1/product/attack-paths',stats:['Attack paths','Critical paths','Nodes','Relationships'],entity:'attack paths',empty:'The current Core exposes attack-path intelligence rather than a standalone IOC feed.'},
 vuln:{title:'Fix what matters first.',eyebrow:'VULNERABILITIES',desc:'Prioritize findings using severity, affected assets and Core risk context.',api:'/v1/product/findings',stats:['Findings','Critical','High','Medium'],entity:'findings',empty:'No findings are available from the current NusaSec Core assessment.'},
 monitor:{title:'See security changes as they happen.',eyebrow:'MONITORING',desc:'Track configuration changes and telemetry coverage from the latest Core assessments.',api:'/v1/product/changes',stats:['Changes','Added','Removed','Coverage'],entity:'changes',empty:'A second scan is required before configuration changes can be calculated.'},
 incidents:{title:'Move from detection to response.',eyebrow:'INCIDENT RESPONSE',desc:'Create and transition incidents through the Core reliability workflow. Read-side incident listing is not currently exposed by the supplied Core API.',api:null,stats:['Read API','Create','Transitions','Audit'],entity:'incidents',empty:'Core currently exposes incident creation and status transitions, but no GET /incidents endpoint.'},
 compliance:{title:'Turn posture into evidence.',eyebrow:'COMPLIANCE',desc:'Use the regulatory applicability layer and Core posture to understand governance scope.',api:'/v1/regulatory/applicability',stats:['Applicability','Regulatory scope','Posture','Evidence'],entity:'applicability',empty:'No regulatory applicability profile is available yet.'}
};
const key=new URLSearchParams(location.search).get('view')||'attack'; const c=cfg[key]||cfg.attack; document.getElementById('crumb').textContent=c.eyebrow;
const esc=v=>String(v??'').replace(/[&<>"']/g,x=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[x]));
const arr=x=>Array.isArray(x)?x:(x?.items||x?.data||x?.results||x?.records||x?.assets||[]);
const api=window.NusaSec?.api;
function normalize(data){ const items=arr(data); if(key==='attack') return items; if(key==='threat') return items; if(key==='monitor') return items; return items; }
function shell(items,state){
root.innerHTML=`<section class="security-workspace"><header class="security-head"><div><div class="eyebrow">${c.eyebrow}</div><h1>${c.title}</h1><p>${c.desc}</p></div><div class="security-actions"><button class="security-btn" id="refresh">Refresh</button>${key==='incidents'?'<button class="security-btn primary" id="create-incident">Create incident</button>':'<button class="security-btn primary" id="focus-action">Investigate</button>'}</div></header><div class="security-toolbar"><input id="q" placeholder="Search ${c.entity}..."/><select id="filter"><option value="">All severity</option><option>CRITICAL</option><option>HIGH</option><option>MEDIUM</option><option>LOW</option></select><span class="data-state">${state}</span></div><div class="security-grid">${c.stats.map((s,i)=>`<div class="security-stat"><span>${s}</span><strong data-stat="${i}">${i===0&&items.length?items.length:'—'}</strong><small>${i===0&&items.length?'from Core':'Core-derived'}</small></div>`).join('')}</div><div class="security-main"><section class="security-panel"><div class="security-panel-head"><strong>${c.entity[0].toUpperCase()+c.entity.slice(1)}</strong><span>${items.length} loaded</span></div><div class="security-list" id="list">${items.length?items.map((x,i)=>{const name=x.name||x.title||x.external_id||x.domain||x.path_id||x.id||`${c.entity.slice(0,-1)} ${i+1}`;const sev=x.severity||x.risk_score||x.status||x.exposure_type||'';return `<button data-i="${i}"><span class="item-name"><strong>${esc(name)}</strong><small>${esc(x.asset_type||x.provider||x.description||x.rule_id||x.status||'NusaSec Core entity')}</small></span><span class="severity ${esc(String(sev).toLowerCase())}">${esc(typeof sev==='number'?sev:sev||'—')}</span></button>`}).join(''):`<div class="empty-security"><strong>${state==='Core unavailable'?'NusaSec Core is unavailable':'No data available'}</strong><span>${c.empty}</span></div>`}</div></section><aside class="security-panel" id="detail"><div class="side-content"><div class="eyebrow">CONTEXT</div><h3>Select an entity</h3><p>Choose a record to inspect its Core-backed context and available actions.</p></div></aside></div></section>`;
items.forEach((x,i)=>document.querySelector(`[data-i="${i}"]`)?.addEventListener('click',()=>select(x)));
if(key==='monitor'&&items.length){const added=items.filter(x=>x.type==='ADDED').length, removed=items.filter(x=>x.type==='REMOVED').length; document.querySelector('[data-stat="1"]').textContent=added; document.querySelector('[data-stat="2"]').textContent=removed;}
if(key==='threat'&&items.length){const critical=items.filter(x=>String(x.severity||'').toUpperCase()==='CRITICAL').length; document.querySelector('[data-stat="1"]').textContent=critical; const nodes=items.reduce((n,x)=>n+(x.nodes?.length||0),0); document.querySelector('[data-stat="2"]').textContent=nodes; const edges=items.reduce((n,x)=>n+Math.max(0,(x.nodes?.length||0)-1),0); document.querySelector('[data-stat="3"]').textContent=edges;}
if(key==='vuln'&&items.length){['CRITICAL','HIGH','MEDIUM'].forEach((s,i)=>document.querySelector(`[data-stat="${i+1}"]`).textContent=items.filter(x=>String(x.severity||'').toUpperCase()===s).length);}
document.getElementById('q')?.addEventListener('input',e=>{const q=e.target.value.toLowerCase();document.querySelectorAll('#list button').forEach(b=>b.hidden=!b.innerText.toLowerCase().includes(q))});document.getElementById('filter')?.addEventListener('change',e=>{const q=e.target.value;document.querySelectorAll('#list button').forEach(b=>b.hidden=!!q&&!b.innerText.toUpperCase().includes(q))});document.getElementById('refresh')?.addEventListener('click',load);
document.getElementById('create-incident')?.addEventListener('click',()=>showCreate());
}
async function select(x){ const d=document.getElementById('detail'); if(!d)return; d.innerHTML='<div class="side-content"><div class="eyebrow">LOADING CONTEXT</div><h3>Resolving from Core…</h3></div>';
let detail=x;
try{if(key==='attack'&&x.id){detail=await api(`/v1/product/assets/${encodeURIComponent(x.id)}/dossier`);} }catch(e){}
const a=detail.asset||detail; d.innerHTML=`<div class="side-content"><div class="eyebrow">ENTITY DETAIL</div><h3>${esc(a.name||a.title||a.external_id||a.path_id||a.id||'Entity')}</h3><p>${esc(a.description||detail.business_context?.application_name||detail.status||'Core-backed security context')}</p>${[['Severity',a.severity||detail.severity||detail.risk_score||'—'],['Status',a.status||detail.status||'—'],['Type',a.asset_type||a.type||'—'],['Provider',a.provider||'—'],['External ID',a.external_id||'—']].map(r=>`<div class="detail-row"><span>${r[0]}</span><b>${esc(r[1])}</b></div>`).join('')}<div class="context-block"><div class="eyebrow">CORE RELATIONSHIPS</div><p>${key==='attack'?(detail.findings?.length||0)+' findings · '+(detail.related_assets?.length||0)+' related assets':key==='threat'?(x.nodes?.length||0)+' path nodes':key==='vuln'?'Finding is evaluated by the Core Risk Engine':key==='monitor'?'Change is derived from scan comparison':'Context is provided by the Core capability above.'}</p></div></div>`;
}
function showCreate(){ const d=document.getElementById('detail'); d.innerHTML='<div class="side-content"><div class="eyebrow">CREATE INCIDENT</div><h3>Start an accountable response</h3><p>The Core exposes POST /api/v1/reliability/incidents. Creation requires the appropriate engineering scope.</p><input id="incident-title" placeholder="Incident title" style="width:100%;padding:10px;margin:12px 0;border:1px solid #ddd;border-radius:7px"><button class="security-btn primary" id="submit-incident">Create</button></div>'; document.getElementById('submit-incident').onclick=async()=>{try{const title=document.getElementById('incident-title').value.trim(); if(!title)return; const r=await api('/v1/reliability/incidents',{method:'POST',body:JSON.stringify({title,severity:'SEV3'})}); d.querySelector('p').textContent=`Created incident #${r.id} · ${r.status}`;}catch(e){d.querySelector('p').textContent='Core rejected the request or is unavailable.'}}; }
async function load(){if(!c.api){shell([],'Core capability mapped; read endpoint unavailable');return;}try{const data=await api(c.api);shell(normalize(data),'Core connected')}catch(e){shell([],'Core unavailable')}} load();
})();
