(() => {
const root=document.getElementById('security-root'); if(!root)return;
const cfg={
 attack:{title:'Know what is exposed.',eyebrow:'ATTACK SURFACE',desc:'Discover internet-facing assets and understand the context behind every exposure.',api:'/attack-surface',stats:['Assets','Internet exposed','High risk','New this week'],entity:'assets',empty:'Assets will appear when the Attack Surface engine provides data.'},
 threat:{title:'Understand what is targeting you.',eyebrow:'THREAT INTELLIGENCE',desc:'Correlate indicators, campaigns and threats with your environment.',api:'/threat-intelligence',stats:['Threats','Indicators','Matches','Active campaigns'],entity:'threats',empty:'Threat intelligence will appear when the engine provides data.'},
 vuln:{title:'Fix what matters first.',eyebrow:'VULNERABILITIES',desc:'Prioritize vulnerabilities using exposure, exploitability and business context.',api:'/vulnerabilities',stats:['Findings','Critical','High','Overdue'],entity:'findings',empty:'Vulnerability findings will appear when the engine provides data.'},
 monitor:{title:'See security as it happens.',eyebrow:'MONITORING',desc:'Follow events and detections across your monitored environment.',api:'/monitoring',stats:['Events','Alerts','Critical alerts','Last hour'],entity:'events',empty:'Events will appear when the Monitoring engine provides data.'},
 incidents:{title:'Move from detection to response.',eyebrow:'INCIDENT RESPONSE',desc:'Investigate incidents through timeline, evidence, affected assets and actions.',api:'/incidents',stats:['Open','Critical','Investigating','Resolved'],entity:'incidents',empty:'Incidents will appear when the response engine provides data.'},
 compliance:{title:'Turn posture into evidence.',eyebrow:'COMPLIANCE',desc:'Connect controls, findings and evidence to the assets they govern.',api:'/compliance',stats:['Frameworks','Controls','Open gaps','Evidence'],entity:'controls',empty:'Controls will appear when the Compliance engine provides data.'}
};
const key=new URLSearchParams(location.search).get('view')||'attack'; const c=cfg[key]||cfg.attack; document.getElementById('crumb').textContent=c.eyebrow.replace('ATTACK SURFACE','Attack Surface').replace('THREAT INTELLIGENCE','Threat Intelligence').replace('INCIDENT RESPONSE','Incidents').replace('COMPLIANCE','Compliance').replace('VULNERABILITIES','Vulnerabilities').replace('MONITORING','Monitoring');
const esc=v=>String(v??'').replace(/[&<>"']/g,x=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[x]));
const arr=x=>Array.isArray(x)?x:(x?.items||x?.data||x?.results||x?.records||x?.[c.entity]||[]);
function shell(items,state){root.innerHTML=`<section class="security-workspace"><header class="security-head"><div><div class="eyebrow">${c.eyebrow}</div><h1>${c.title}</h1><p>${c.desc}</p></div><div class="security-actions"><button class="security-btn" id="refresh">Refresh</button><button class="security-btn primary">Investigate</button></div></header><div class="security-toolbar"><input id="q" placeholder="Search ${c.entity}..."/><select id="filter"><option value="">All severity</option><option>Critical</option><option>High</option><option>Medium</option><option>Low</option></select><span class="data-state">${state}</span></div><div class="security-grid">${c.stats.map((s,i)=>`<div class="security-stat"><span>${s}</span><strong>${items.length&&i===0?items.length:'—'}</strong><small>${i===0&&items.length?'from Core':'Awaiting Core data'}</small></div>`).join('')}</div><div class="security-main"><section class="security-panel"><div class="security-panel-head"><strong>${c.entity[0].toUpperCase()+c.entity.slice(1)}</strong><span>${items.length} loaded</span></div><div class="security-list" id="list">${items.length?items.map((x,i)=>{const name=x.name||x.title||x.domain||x.hostname||x.id||`${c.entity.slice(0,-1)} ${i+1}`;const sev=x.severity||x.risk||x.priority||'';return `<button data-i="${i}"><span class="item-name"><strong>${esc(name)}</strong><small>${esc(x.type||x.status||x.description||'NusaSec Core entity')}</small></span><span class="severity ${esc(String(sev).toLowerCase())}">${esc(sev||'—')}</span></button>`}).join(''):`<div class="empty-security"><strong>${state==='Core unavailable'?'NusaSec Core is unavailable':'Waiting for NusaSec Core'}</strong><span>${c.empty}</span></div>`}</div></section><aside class="security-panel" id="detail"><div class="side-content"><div class="eyebrow">CONTEXT</div><h3>Select an entity</h3><p>Choose a record to inspect its relationships, risk context and available actions.</p></div></aside></div></section>`;
items.forEach((x,i)=>document.querySelector(`[data-i="${i}"]`)?.addEventListener('click',()=>{const d=document.getElementById('detail');d.innerHTML=`<div class="side-content"><div class="eyebrow">ENTITY DETAIL</div><h3>${esc(x.name||x.title||x.domain||x.hostname||x.id||'Entity')}</h3><p>${esc(x.description||x.status||'Context from NusaSec Core')}</p>${[['Severity',x.severity||x.risk||'—'],['Status',x.status||'—'],['Type',x.type||'—'],['ID',x.id||'—']].map(r=>`<div class="detail-row"><span>${r[0]}</span><b>${esc(r[1])}</b></div>`).join('')}<div class="context-block"><div class="eyebrow">NEXT ACTION</div><p>Related assets, threats, findings and remediation actions can be resolved here from Core relationships.</p></div></div>`}));
document.getElementById('q')?.addEventListener('input',e=>{const q=e.target.value.toLowerCase();document.querySelectorAll('#list button').forEach(b=>b.hidden=!b.innerText.toLowerCase().includes(q))});document.getElementById('refresh')?.addEventListener('click',load);
}
async function load(){try{const r=await fetch(`/api${c.api}`,{credentials:'include'});if(!r.ok)throw Error(r.status);shell(arr(await r.json()),'Core connected')}catch(e){shell([],'Core unavailable')}} load();
})();
